//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thecfhouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPro
    {
        public int MADATHANG { get; set; }
        public Nullable<int> MASP { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<int> MAKH { get; set; }
        public string DIACHIGIAOHANG { get; set; }
        public string MATHANHTOAN { get; set; }
        public string PHUONGTHUCTTHANHTOAN { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
